### ISSUE TITLE
Upgrade scalacheck to 1.14.0

### ISSUE THREAD

**Issue by avdv** [typelevel/cats#2449]
I am using specs2 4.3.x and I want to use cats-laws with it.

Unfortunately, [specs2-scalacheck](http://www.mvnrepository.com/artifact/org.specs2/specs2-scalacheck_2.12/4.3.4) >= 4.2.0 requires scalacheck 1.14.0 but [cats-laws](http://www.mvnrepository.com/artifact/org.typelevel/cats-laws_2.12/1.2.0) 1.2.0 is build with scalacheck 1.13.5 which is [binary incompatible with each other](https://github.com/rickynils/scalacheck/blob/1.14.0/CHANGELOG.markdown).

This results in the following runtime exception:
```
[error] cannot create an instance for class com.rub.models.resources.ParamSpec
[error]   caused by java.lang.NoSuchMethodError: org.scalacheck.Cogen$.apply(Lorg/scalacheck/Cogen;Lorg/scalacheck/Cogen;)Lorg/scalacheck/Cogen;
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]   org.specs2.reflect.Classes.$anonfun$createInstanceForConstructor$1(Classes.scala:69)
[error]   org.specs2.reflect.Classes.newInstance(Classes.scala:91)
```

**Comment by johnynek** [comment]
We can't do that until we break binary compatibility (cats 3.0 is our current plan, cats 2.0 will be binary compatible for scala 2.12, but not 2.11). scalacheck should ideally be using mima, and they should have bumped to scalacheck 2.0.0.

cc @non

**Comment by rossabaker** [comment]
There is a deeper discussion of this on https://github.com/typelevel/cats/pull/2312 with a possible solution for cats-1.x.

**Comment by johnynek** [comment]
@SethTisue cats-laws is not test-only, for that artifact, scalacheck is a regular dependency.

**Comment by kailuowang** [comment]
This has been done.
