### PR TITLE
Fix source compatibility with Scala 3.6.3

### PR DESCRIPTION
**Pull request by mbovel**
While trying to update Cats in the Dotty community build (a list of projects that the Dotty CI compiles on every push) (see https://github.com/scala/scala3/pull/22949), I found that Cats currently doesn't compile with Scala 3.6.3 for two reasons:

1. When calling a function with implicit parameters, it is now required to explicit pass arguments prefixed with `using`.

    Here is a minimal reproduction:

    ```scala
    package using1
    
    trait Hash[T]
    trait Order[T]
    
    def catsKernelStdHashForSortedSet[X: Hash] = ???
    def catsKernelStdHashForSortedSet[X: Order, Y: Hash] = ???
    
    @main def main =
      val intHash: Hash[Int] = ???
      catsKernelStdHashForSortedSet(intHash)
    ```

    Compiles with Scala 3.3.4:

    ```
    $ scala compile -S 3.3.4 using1.scala
    ```

    Does not compile with Scala 3.6.3:

    ```scala
    $ scala compile -S 3.6.3 using1.scala
    Compiling project (Scala 3.6.3, JVM (21))
    [error] ./using1.scala:11:3
    [error] None of the overloaded alternatives of method catsKernelStdHashForSortedSet in package using1 with types
    [error]  [X, Y](using evidence$1: using1.Order[X], evidence$2: using1.Hash[Y]): Nothing
    [error]  [X](using evidence$1: using1.Hash[X]): Nothing
    [error] match arguments ((intHash : using1.Hash[Int]))
    [error]   catsKernelStdHashForSortedSet(intHash)
    [error]   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error compiling project (Scala 3.6.3, JVM (21))
    Compilation failed
    ```

     Instead, a `using` is required before `intHash`:

    ```scala
      catsKernelStdHashForSortedSet(using intHash)
    ```
    
    Note: this change has already been made in at least one other typelevel project: https://github.com/typelevel/doobie/pull/2228.

2. When using a pattern in a for loop that is more specialized than the right hand-side, Scala 3.3.4 emitted a warning:

    ```scala
    package for_case

    @main def main =
      val o: List[Option[Int]] = List(Some(42))
      for Some(x) <- o do
        print(x)
    ```

    ```scala
    $ scala compile -S 3.3.4 for_case.scala
    Compiling project (Scala 3.3.4, JVM (21))
    [warn] ./for_case.scala:5:7
    [warn] pattern's type Some[Int] is more specialized than the right hand side expression's type Option[Int]
    [warn] 
    [warn] If the narrowing is intentional, this can be communicated by adding the `case` keyword before the full pattern,
    [warn] which will result in a filtering for expression (using `withFilter`).
    [warn] This patch can be rewritten automatically under -rewrite -source 3.2-migration.
    [warn]   for Some(x) <- o do
    [warn]       ^^^^^^^
    Compiled project (Scala 3.3.4, JVM (21))
    ```

    This is now an error in Scala 3.6.3.

This PR updates both cases so that Cats compiles with Scala 3.6.3.

These changes should remain compatible with Scala 2.12 and 2.13.

Note: I also tried to apply the automatic rewrites from Scala 3.4 to reduce the number of warnings (see https://github.com/dotty-staging/cats/commit/5ea50ee3c051f02890cd529c22ca300bc0d710e5), but those changes are not compatible with Scala 2.12 and 2.13, so I have not included them.

### CODE REVIEW

**Review by djspiewak — APPROVED** [review]
Thank you!

**Review by LukaJCB — APPROVED** [review]
