### ISSUE TITLE
Spark 3 / Cats 2.2.0 classpath issue

### ISSUE THREAD

**Issue by samidalouche** [typelevel/cats#3628]
A small project with minimal dependencies as well as instructions on how to reproduce the issue is available at:

https://github.com/samidalouche/spark3-cats220

Executing this code works fine with cats `2.1.1` but fails with cats `2.2.0`, which is quite surprising since the spark and cats dependencies are pretty much distinct from each other. 

```
java.lang.NoSuchMethodError: 'void cats.kernel.CommutativeSemigroup.$init$(cats.kernel.CommutativeSemigroup)'
  at cats.UnorderedFoldable$$anon$1.<init>(UnorderedFoldable.scala:78)
  at cats.UnorderedFoldable$.<init>(UnorderedFoldable.scala:78)
  at cats.UnorderedFoldable$.<clinit>(UnorderedFoldable.scala)
  at cats.data.NonEmptyListInstances$$anon$2.<init>(NonEmptyList.scala:539)
  at cats.data.NonEmptyListInstances.<init>(NonEmptyList.scala:539)
  at cats.data.NonEmptyList$.<init>(NonEmptyList.scala:458)
  at cats.data.NonEmptyList$.<clinit>(NonEmptyList.scala)
  at catsspark.Boom$.assumeValid_$bang(boom.scala:19)
  at catsspark.Boom$.boom(boom.scala:14)
  ... 47 elided
```

Thanks in advance for looking into this.

I submitted the same issue to spark's bug tracker: https://issues.apache.org/jira/browse/SPARK-33077

**Comment by Jasper-M** [comment]
Spark seems to have a (possibly transitive) dependency on cats-kernel 2.0.0-M4 (!) which seems to be confirmed by that stacktrace and [this list of dependencies](https://github.com/apache/spark/blob/v3.0.1/dev/deps/spark-deps-hadoop-2.7-hive-2.3#L29).

**Comment by samidalouche** [comment]
@Jasper-M Thanks, you are right indeed. Spark 3 has a dependency on cats-kernel_2.12-2.0.0-M4.jar that spark 2.4 did not have. Thanks for looking into this.

**Comment by Jasper-M** [comment]
Looks like spark-mllib depends on breeze 1.0 which depends on a milestone version of Spire and so on.

**Comment by djspiewak** [comment]
This definitely needs to be reopened on Spark's issue tracker. Cats doesn't guarantee binary compatibility with milestones. If they can update their dependency to at least 2.0.0, the problem will go away. In the short term, users can probably work around this by `exclude`ing the transitive dependency coming in via Spark.

**Comment by djspiewak** [comment]
Holy crap…

**Comment by mcanlas** [comment]
Better double check that Spark is working on it since the filed issue (Spark side) is currently closed.

**Comment by chrilves** [comment]
I managed to get rid of a similar error by setting these two options via spak-submit

```
--conf spark.driver.userClassPathFirst=true
--conf spark.executor.userClassPathFirst=true
```

I don't know how safe it though.

**Comment by samthebest** [comment]
To make it easier for googlers to find something to copy and paste, here, copy pasta this into your `build.sbt`

```
assembly / assemblyShadeRules := Seq(
        ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll,
        ShadeRule.rename("cats.kernel.**" -> s"new_cats.kernel.@1").inAll
      ),
```

**Comment by kennyishihara** [comment]
> To make it easier for googlers to find something to copy and paste, here, copy pasta this into your `build.sbt`
> 
> ```
> assembly / assemblyShadeRules := Seq(
>         ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll,
>         ShadeRule.rename("cats.kernel.**" -> s"new_cats.kernel.@1").inAll
>       ),
> ```

Excellent!

And for `build.gradle` using [shadow plugin](https://imperceptiblethoughts.com/shadow/), this worked
```
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
            allowInsecureProtocol = true
        }
        mavenCentral()
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:6.1.0"
    }
}

apply plugin: "com.github.johnrengelman.shadow"

shadowJar {
    ...
    relocate "shapeless", "shadow.shapeless"
    relocate "cats.kernel", "shadow.kernel"
}
```

**Comment by pak21** [comment]
Just a 2024 update for the wanderers into this issue: even though [SPARK-33077](https://issues.apache.org/jira/browse/SPARK-33077) is closed and recent Databricks runtimes use cats 2.1.1, you still need to shade cats if you're using a more recent version of cats. I haven't dug into why.

**Comment by rossabaker** [comment]
I suspect it's because of the issue Jasper mentioned upthread: Cats, like most libraries, isn't *bidirectionally* binary compatible.  The older version in the Databricks runtime effectively evicts whatever newer version you're compiling against unless you shade.
